/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package W6;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author haika
 */
public class GUI extends javax.swing.JFrame {
    private Player dafa;
    private Enemy slime;
    private boolean battle = false;
    private boolean chooseClass = false;
    private int classN;
    private Stage alur = new Stage();
    private Equipment equipment = new Equipment();
    private NPC udin = new NPC(10,10,10);
    private int idxDialogue = 0;
    public GUI() {
        initComponents();
        NamaPlayer.setVisible(false);
        Attack_button.setVisible(false);
        udin.SetType();
        udin.SetDiag();
        winorlose.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelHP = new javax.swing.JLabel();
        labelAtk = new javax.swing.JLabel();
        labelDef = new javax.swing.JLabel();
        NamaPlayer = new javax.swing.JLabel();
        ValueHP = new javax.swing.JLabel();
        ValueAtk = new javax.swing.JLabel();
        ValueDef = new javax.swing.JLabel();
        Attack_button = new javax.swing.JButton();
        Stage = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Okbutton = new javax.swing.JButton();
        GetNamePlayer = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button_assasin = new javax.swing.JButton();
        button_guardian = new javax.swing.JButton();
        button_necromancer = new javax.swing.JButton();
        button_archer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        HPMusuh = new javax.swing.JProgressBar();
        Player = new javax.swing.JLabel();
        EnemyLabel = new javax.swing.JLabel();
        winorlose = new javax.swing.JPanel();
        afterbattle = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ClassQ = new javax.swing.JLabel();
        ChoosenClass = new javax.swing.JLabel();
        Yesclass = new javax.swing.JButton();
        Noclass = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        boxdialog1 = new javax.swing.JPanel();
        labelbox = new javax.swing.JLabel();
        Opsi1 = new javax.swing.JButton();
        Opsi2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 206));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHP.setText("HP      : ");
        jPanel1.add(labelHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 47, -1, -1));

        labelAtk.setText("Attack : ");
        jPanel1.add(labelAtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 119, -1, -1));

        labelDef.setText("Def     : ");
        jPanel1.add(labelDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 82, -1, -1));

        NamaPlayer.setText("Nama Petualang");
        jPanel1.add(NamaPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, -1, -1));

        ValueHP.setText("ValueHP");
        jPanel1.add(ValueHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 47, -1, -1));

        ValueAtk.setText("ValueAtk");
        jPanel1.add(ValueAtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 119, -1, -1));

        ValueDef.setText("ValueDef");
        jPanel1.add(ValueDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 82, -1, -1));

        Attack_button.setText("Attack");
        Attack_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attack_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Attack_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 44, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 720, 200));

        Stage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                StageStateChanged(evt);
            }
        });

        jLabel1.setText("Masukan Nama Petualang:");

        Okbutton.setText("OK");
        Okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkbuttonActionPerformed(evt);
            }
        });

        GetNamePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNamePlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GetNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Okbutton)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Okbutton))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        Stage.addTab("tab1", jPanel2);

        jLabel2.setText("Pilih Class ");

        button_assasin.setText("Assasin");
        button_assasin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_assasinActionPerformed(evt);
            }
        });

        button_guardian.setText("Guardian");
        button_guardian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_guardianActionPerformed(evt);
            }
        });

        button_necromancer.setText("Necromancer");
        button_necromancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_necromancerActionPerformed(evt);
            }
        });

        button_archer.setText("Archer");
        button_archer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_archerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_guardian, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_assasin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_necromancer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_archer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(button_assasin)
                .addGap(18, 18, 18)
                .addComponent(button_guardian)
                .addGap(18, 18, 18)
                .addComponent(button_necromancer)
                .addGap(18, 18, 18)
                .addComponent(button_archer)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        Stage.addTab("tab2", jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(720, 250));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HPMusuh.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        HPMusuh.setMaximum(200);
        HPMusuh.setToolTipText("");
        HPMusuh.setValue(200);
        HPMusuh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        HPMusuh.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                HPMusuhStateChanged(evt);
            }
        });
        jPanel4.add(HPMusuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 57, -1, 10));

        Player.setText("Player");
        jPanel4.add(Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 168, -1, -1));

        EnemyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnemyLabel.setText("Enemy");
        jPanel4.add(EnemyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 73, 146, -1));

        winorlose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winorloseMouseClicked(evt);
            }
        });
        winorlose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        afterbattle.setText("|");
        winorlose.add(afterbattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel4.add(winorlose, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 450, 30));

        Stage.addTab("tab3", jPanel4);

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel3.setText("MENANG ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel3)
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel3)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        Stage.addTab("tab4", jPanel6);

        ClassQ.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        ClassQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClassQ.setText("APAKAH ANDA YAKIN AKAN MEMILIH CLASS");
        ClassQ.setMaximumSize(new java.awt.Dimension(200, 200));

        ChoosenClass.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        ChoosenClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChoosenClass.setText("class");

        Yesclass.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        Yesclass.setText("YA");
        Yesclass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        Yesclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesclassActionPerformed(evt);
            }
        });

        Noclass.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        Noclass.setText("Tidak");
        Noclass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        Noclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoclassActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("(Class Tidak akan bisa berubah Di lain waktu)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(ClassQ, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(Yesclass, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(Noclass, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(ChoosenClass, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(ClassQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChoosenClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Noclass)
                    .addComponent(Yesclass))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        Stage.addTab("tab5", jPanel5);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxdialog1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boxdialog1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxdialog1MouseClicked(evt);
            }
        });
        boxdialog1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelbox.setText("|");
        boxdialog1.add(labelbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        jPanel7.add(boxdialog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 650, 100));

        Opsi1.setText("Opsi1");
        Opsi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi1ActionPerformed(evt);
            }
        });
        jPanel7.add(Opsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        Opsi2.setText("Opsi2");
        Opsi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opsi2ActionPerformed(evt);
            }
        });
        jPanel7.add(Opsi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        Stage.addTab("tab6", jPanel7);

        getContentPane().add(Stage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Timer(){
        Timer timer = new Timer(1000, new ActionListener() { // Delay 1 detik (1000 milidetik)
            public void actionPerformed(ActionEvent e) {
                // Proses yang akan dilakukan setelah delay
                getAlur().run();
            if (getAlur().getCurrentInteraction() < getAlur().getMAX_INTERACTIONS() ){
                if (getAlur().isBattle() == true){
                        getStage().setSelectedIndex(3);
                        getStage().setSelectedIndex(2);
                }else{
                        getStage().setSelectedIndex(3);
                        getStage().setSelectedIndex(5);
                }
            }else{
                    getStage().setSelectedIndex(3);
            }
                getAlur().setCurrentInteraction(getAlur().getCurrentInteraction() + 1);
                getAlur().setBattle(true);
                getWinorlose().setVisible(false);
                getLabelbox().setText("|");
            }
        });
        timer.setRepeats(false); // Setel agar timer hanya berjalan satu kali
        timer.start(); // Memulai timer
         // error still
    }
    private void GetNamePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNamePlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetNamePlayerActionPerformed

    private void OkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkbuttonActionPerformed
        // TODO add your handling code here:
        if (!GetNamePlayer.getText().equals("")){
            String nama = getGetNamePlayer().getText();
            setDafa(new Player(nama, 200,100,100));
            getNamaPlayer().setText(getDafa().getNama());
            getNamaPlayer().setVisible(true);
            getValueHP().setText(getDafa().getHP() +"");
            getValueDef().setText(getDafa().getDefense() + "");
            getValueAtk().setText(getDafa().getAttack_point() + "");
            getStage().setSelectedIndex(1);
            
        }
        
    }//GEN-LAST:event_OkbuttonActionPerformed

    private void Attack_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attack_buttonActionPerformed
        getDafa().attack(getSlime());
        
        getHPMusuh().setValue(getSlime().getHP());
        getSlime().attack(getDafa());
        ChangeHP();
        if (getSlime().getHP() < 0){
            
            getDafa().setHP(getDafa().getMaxHP());
            ChangeHP();
            Timer timer = new Timer(1000, new ActionListener() { // Delay 3 detik (3000 milidetik)
            public void actionPerformed(ActionEvent e) {
                // Proses yang akan dilakukan setelah delay
                    getWinorlose().setVisible(true);
                    getWinorlose().setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
                    getAfterbattle().setText("Anda Berhasil Mengalahkan Musuh");
            }
        });
        timer.setRepeats(false); // Setel agar timer hanya berjalan satu kali
        timer.start(); // Memulai timer
            
//            Stage.setSelectedIndex(Stage.getSelectedIndex() + 1);
        }
    }//GEN-LAST:event_Attack_buttonActionPerformed

    private void StageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_StageStateChanged
        // TODO add your handling code here:
        
        
        if (getAlur().isBattle() == true){
            getAttack_button().setVisible(true);
            setSlime(new Enemy("Slime", 200, 100, 100));
            getHPMusuh().setMaximum(getSlime().getHP());
            getHPMusuh().setValue(getSlime().getHP());
        }else{
            getAttack_button().setVisible(false);
        }
        // error still
        
    }//GEN-LAST:event_StageStateChanged

    private void button_assasinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_assasinActionPerformed
        // TODO add your handling code here:
        setClassN(1);
        getDafa().tipeClass(getClassN());
        getChoosenClass().setText(getDafa().dapatkanClass());
        this.getStage().setSelectedIndex(4);
    }//GEN-LAST:event_button_assasinActionPerformed

    private void button_guardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_guardianActionPerformed
        // TODO add your handling code here:
        setClassN(2);
        getDafa().tipeClass(getClassN());
        getChoosenClass().setText(getDafa().dapatkanClass());
        this.getStage().setSelectedIndex(4);
    }//GEN-LAST:event_button_guardianActionPerformed

    private void HPMusuhStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_HPMusuhStateChanged
        // TODO add your handling code here:
        getHPMusuh().setValue(getSlime().getHP());
    }//GEN-LAST:event_HPMusuhStateChanged

    private void YesclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesclassActionPerformed
        // TODO add your handling code here:
        getEquipment().EquipmentInit(getDafa());
        getEquipment().EquipmentsetforClass(getDafa());
        ChangeAttr();
        
        getDafa().setMaxHP();

        getUdin().reward1.EquipmentInit(getDafa());
        getUdin().reward2.EquipmentInit(getDafa());
        getUdin().setReward();
        getAlur().run();
        if (getAlur().isBattle() == true){
            getStage().setSelectedIndex(2);
        }else{
            getStage().setSelectedIndex(5);
        }
        getAlur().setCurrentInteraction(getAlur().getCurrentInteraction() + 1);
         // error still
    }//GEN-LAST:event_YesclassActionPerformed

    private void NoclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoclassActionPerformed
        getStage().setSelectedIndex(1);
    }//GEN-LAST:event_NoclassActionPerformed

    private void boxdialog1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxdialog1MouseClicked
        // TODO add your handling code here:
        String[] textNPC = new String[5];
        System.out.println(textNPC.length);
        textNPC = getUdin().getDialogue();
        try {
            if (getIdxDialogue() == textNPC.length -1) {
                throw new Exception("Sudah max idx");
            }
            if (getIdxDialogue()<textNPC.length){
                getLabelbox().setText(textNPC[getIdxDialogue()]);
                setIdxDialogue(getIdxDialogue() + 1);
                if(textNPC[getIdxDialogue()]==null && getIdxDialogue() < textNPC.length){
                    setIdxDialogue(getIdxDialogue() + 1);
                }
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_boxdialog1MouseClicked

    private void winorloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winorloseMouseClicked
        // TODO add your handling code here:
        /*Timer timer = new Timer(3000, new ActionListener() { // Delay 3 detik (3000 milidetik)
            public void actionPerformed(ActionEvent e) {
                // Proses yang akan dilakukan setelah delay
                winorlose.setVisible(false);
                 alur.run();
            if (alur.getCurrentInteraction() < alur.getMAX_INTERACTIONS() ){
                if (alur.isBattle() == true){
                    Stage.setSelectedIndex(3);
                    Stage.setSelectedIndex(2);
                }else{
                    Stage.setSelectedIndex(3);
                    Stage.setSelectedIndex(5);
                }
            }else{
                Stage.setSelectedIndex(3);
            }
            alur.setCurrentInteraction(alur.getCurrentInteraction() + 1);
            }
        });
        timer.setRepeats(false); // Setel agar timer hanya berjalan satu kali
        timer.start(); // Memulai timer
         // error still
           */
        Timer();
    }//GEN-LAST:event_winorloseMouseClicked

    private void button_necromancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_necromancerActionPerformed
        // TODO add your handling code here:
        setClassN(3); 
        getDafa().tipeClass(getClassN());
        getChoosenClass().setText(getDafa().dapatkanClass());
        this.getStage().setSelectedIndex(4);
    }//GEN-LAST:event_button_necromancerActionPerformed

    private void button_archerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_archerActionPerformed
        // TODO add your handling code here:
        setClassN(4);
        getDafa().tipeClass(getClassN());
        getChoosenClass().setText(getDafa().dapatkanClass());
        this.getStage().setSelectedIndex(4);
    }//GEN-LAST:event_button_archerActionPerformed

    private void Opsi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi1ActionPerformed
        int pilih;
        pilih = 1;
        getUdin().pilihReward(getDafa(), pilih);
        Timer();
    }//GEN-LAST:event_Opsi1ActionPerformed

    private void Opsi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opsi2ActionPerformed
        int pilih;
        pilih = 2;
        getUdin().pilihReward(getDafa(), pilih);
        Timer();
    }//GEN-LAST:event_Opsi2ActionPerformed
    public void ChangeAttr(){
        ChangeHP();
        ChangeDef();
        ChangeAtk();
    }
    public void ChangeHP(){
        getValueHP().setText(getDafa().getHP() + "");
    }
    public void ChangeDef(){
        getValueDef().setText(getDafa().getDefense() +"");
    }
    
    public void ChangeAtk(){
        getValueAtk().setText(getDafa().getAttack_point() + "");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attack_button;
    private javax.swing.JLabel ChoosenClass;
    private javax.swing.JLabel ClassQ;
    private javax.swing.JLabel EnemyLabel;
    private javax.swing.JTextField GetNamePlayer;
    private javax.swing.JProgressBar HPMusuh;
    private javax.swing.JLabel NamaPlayer;
    private javax.swing.JButton Noclass;
    private javax.swing.JButton Okbutton;
    private javax.swing.JButton Opsi1;
    private javax.swing.JButton Opsi2;
    private javax.swing.JLabel Player;
    private javax.swing.JTabbedPane Stage;
    private javax.swing.JLabel ValueAtk;
    private javax.swing.JLabel ValueDef;
    private javax.swing.JLabel ValueHP;
    private javax.swing.JButton Yesclass;
    private javax.swing.JLabel afterbattle;
    private javax.swing.JPanel boxdialog1;
    private javax.swing.JButton button_archer;
    private javax.swing.JButton button_assasin;
    private javax.swing.JButton button_guardian;
    private javax.swing.JButton button_necromancer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelAtk;
    private javax.swing.JLabel labelDef;
    private javax.swing.JLabel labelHP;
    private javax.swing.JLabel labelbox;
    private javax.swing.JPanel winorlose;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dafa
     */
    public Player getDafa() {
        return dafa;
    }

    /**
     * @param dafa the dafa to set
     */
    public void setDafa(Player dafa) {
        this.dafa = dafa;
    }

    /**
     * @return the slime
     */
    public Enemy getSlime() {
        return slime;
    }

    /**
     * @param slime the slime to set
     */
    public void setSlime(Enemy slime) {
        this.slime = slime;
    }

    /**
     * @return the battle
     */
    public boolean isBattle() {
        return battle;
    }

    /**
     * @param battle the battle to set
     */
    public void setBattle(boolean battle) {
        this.battle = battle;
    }

    /**
     * @return the chooseClass
     */
    public boolean isChooseClass() {
        return chooseClass;
    }

    /**
     * @param chooseClass the chooseClass to set
     */
    public void setChooseClass(boolean chooseClass) {
        this.chooseClass = chooseClass;
    }

    /**
     * @return the classN
     */
    public int getClassN() {
        return classN;
    }

    /**
     * @param classN the classN to set
     */
    public void setClassN(int classN) {
        this.classN = classN;
    }

    /**
     * @return the alur
     */
    public Stage getAlur() {
        return alur;
    }

    /**
     * @param alur the alur to set
     */
    public void setAlur(Stage alur) {
        this.alur = alur;
    }

    /**
     * @return the equipment
     */
    public Equipment getEquipment() {
        return equipment;
    }

    /**
     * @param equipment the equipment to set
     */
    public void setEquipment(Equipment equipment) {
        this.equipment = equipment;
    }

    /**
     * @return the udin
     */
    public NPC getUdin() {
        return udin;
    }

    /**
     * @param udin the udin to set
     */
    public void setUdin(NPC udin) {
        this.udin = udin;
    }

    /**
     * @return the idxDialogue
     */
    public int getIdxDialogue() {
        return idxDialogue;
    }

    /**
     * @param idxDialogue the idxDialogue to set
     */
    public void setIdxDialogue(int idxDialogue) {
        this.idxDialogue = idxDialogue;
    }

    /**
     * @return the Attack_button
     */
    public javax.swing.JButton getAttack_button() {
        return Attack_button;
    }

    /**
     * @param Attack_button the Attack_button to set
     */
    public void setAttack_button(javax.swing.JButton Attack_button) {
        this.Attack_button = Attack_button;
    }

    /**
     * @return the ChoosenClass
     */
    public javax.swing.JLabel getChoosenClass() {
        return ChoosenClass;
    }

    /**
     * @param ChoosenClass the ChoosenClass to set
     */
    public void setChoosenClass(javax.swing.JLabel ChoosenClass) {
        this.ChoosenClass = ChoosenClass;
    }

    /**
     * @return the ClassQ
     */
    public javax.swing.JLabel getClassQ() {
        return ClassQ;
    }

    /**
     * @param ClassQ the ClassQ to set
     */
    public void setClassQ(javax.swing.JLabel ClassQ) {
        this.ClassQ = ClassQ;
    }

    /**
     * @return the EnemyLabel
     */
    public javax.swing.JLabel getEnemyLabel() {
        return EnemyLabel;
    }

    /**
     * @param EnemyLabel the EnemyLabel to set
     */
    public void setEnemyLabel(javax.swing.JLabel EnemyLabel) {
        this.EnemyLabel = EnemyLabel;
    }

    /**
     * @return the GetNamePlayer
     */
    public javax.swing.JTextField getGetNamePlayer() {
        return GetNamePlayer;
    }

    /**
     * @param GetNamePlayer the GetNamePlayer to set
     */
    public void setGetNamePlayer(javax.swing.JTextField GetNamePlayer) {
        this.GetNamePlayer = GetNamePlayer;
    }

    /**
     * @return the HPMusuh
     */
    public javax.swing.JProgressBar getHPMusuh() {
        return HPMusuh;
    }

    /**
     * @param HPMusuh the HPMusuh to set
     */
    public void setHPMusuh(javax.swing.JProgressBar HPMusuh) {
        this.HPMusuh = HPMusuh;
    }

    /**
     * @return the NamaPlayer
     */
    public javax.swing.JLabel getNamaPlayer() {
        return NamaPlayer;
    }

    /**
     * @param NamaPlayer the NamaPlayer to set
     */
    public void setNamaPlayer(javax.swing.JLabel NamaPlayer) {
        this.NamaPlayer = NamaPlayer;
    }

    /**
     * @return the Noclass
     */
    public javax.swing.JButton getNoclass() {
        return Noclass;
    }

    /**
     * @param Noclass the Noclass to set
     */
    public void setNoclass(javax.swing.JButton Noclass) {
        this.Noclass = Noclass;
    }

    /**
     * @return the Okbutton
     */
    public javax.swing.JButton getOkbutton() {
        return Okbutton;
    }

    /**
     * @param Okbutton the Okbutton to set
     */
    public void setOkbutton(javax.swing.JButton Okbutton) {
        this.Okbutton = Okbutton;
    }

    /**
     * @return the Opsi1
     */
    public javax.swing.JButton getOpsi1() {
        return Opsi1;
    }

    /**
     * @param Opsi1 the Opsi1 to set
     */
    public void setOpsi1(javax.swing.JButton Opsi1) {
        this.Opsi1 = Opsi1;
    }

    /**
     * @return the Opsi2
     */
    public javax.swing.JButton getOpsi2() {
        return Opsi2;
    }

    /**
     * @param Opsi2 the Opsi2 to set
     */
    public void setOpsi2(javax.swing.JButton Opsi2) {
        this.Opsi2 = Opsi2;
    }

    /**
     * @return the Player
     */
    public javax.swing.JLabel getPlayer() {
        return Player;
    }

    /**
     * @param Player the Player to set
     */
    public void setPlayer(javax.swing.JLabel Player) {
        this.Player = Player;
    }

    /**
     * @return the Stage
     */
    public javax.swing.JTabbedPane getStage() {
        return Stage;
    }

    /**
     * @param Stage the Stage to set
     */
    public void setStage(javax.swing.JTabbedPane Stage) {
        this.Stage = Stage;
    }

    /**
     * @return the ValueAtk
     */
    public javax.swing.JLabel getValueAtk() {
        return ValueAtk;
    }

    /**
     * @param ValueAtk the ValueAtk to set
     */
    public void setValueAtk(javax.swing.JLabel ValueAtk) {
        this.ValueAtk = ValueAtk;
    }

    /**
     * @return the ValueDef
     */
    public javax.swing.JLabel getValueDef() {
        return ValueDef;
    }

    /**
     * @param ValueDef the ValueDef to set
     */
    public void setValueDef(javax.swing.JLabel ValueDef) {
        this.ValueDef = ValueDef;
    }

    /**
     * @return the ValueHP
     */
    public javax.swing.JLabel getValueHP() {
        return ValueHP;
    }

    /**
     * @param ValueHP the ValueHP to set
     */
    public void setValueHP(javax.swing.JLabel ValueHP) {
        this.ValueHP = ValueHP;
    }

    /**
     * @return the Yesclass
     */
    public javax.swing.JButton getYesclass() {
        return Yesclass;
    }

    /**
     * @param Yesclass the Yesclass to set
     */
    public void setYesclass(javax.swing.JButton Yesclass) {
        this.Yesclass = Yesclass;
    }

    /**
     * @return the afterbattle
     */
    public javax.swing.JLabel getAfterbattle() {
        return afterbattle;
    }

    /**
     * @param afterbattle the afterbattle to set
     */
    public void setAfterbattle(javax.swing.JLabel afterbattle) {
        this.afterbattle = afterbattle;
    }

    /**
     * @return the boxdialog1
     */
    public javax.swing.JPanel getBoxdialog1() {
        return boxdialog1;
    }

    /**
     * @param boxdialog1 the boxdialog1 to set
     */
    public void setBoxdialog1(javax.swing.JPanel boxdialog1) {
        this.boxdialog1 = boxdialog1;
    }

    /**
     * @return the button_archer
     */
    public javax.swing.JButton getButton_archer() {
        return button_archer;
    }

    /**
     * @param button_archer the button_archer to set
     */
    public void setButton_archer(javax.swing.JButton button_archer) {
        this.button_archer = button_archer;
    }

    /**
     * @return the button_assasin
     */
    public javax.swing.JButton getButton_assasin() {
        return button_assasin;
    }

    /**
     * @param button_assasin the button_assasin to set
     */
    public void setButton_assasin(javax.swing.JButton button_assasin) {
        this.button_assasin = button_assasin;
    }

    /**
     * @return the button_guardian
     */
    public javax.swing.JButton getButton_guardian() {
        return button_guardian;
    }

    /**
     * @param button_guardian the button_guardian to set
     */
    public void setButton_guardian(javax.swing.JButton button_guardian) {
        this.button_guardian = button_guardian;
    }

    /**
     * @return the button_necromancer
     */
    public javax.swing.JButton getButton_necromancer() {
        return button_necromancer;
    }

    /**
     * @param button_necromancer the button_necromancer to set
     */
    public void setButton_necromancer(javax.swing.JButton button_necromancer) {
        this.button_necromancer = button_necromancer;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @param jPanel4 the jPanel4 to set
     */
    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @param jPanel5 the jPanel5 to set
     */
    public void setjPanel5(javax.swing.JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    /**
     * @return the jPanel6
     */
    public javax.swing.JPanel getjPanel6() {
        return jPanel6;
    }

    /**
     * @param jPanel6 the jPanel6 to set
     */
    public void setjPanel6(javax.swing.JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    /**
     * @return the jPanel7
     */
    public javax.swing.JPanel getjPanel7() {
        return jPanel7;
    }

    /**
     * @param jPanel7 the jPanel7 to set
     */
    public void setjPanel7(javax.swing.JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    /**
     * @return the labelAtk
     */
    public javax.swing.JLabel getLabelAtk() {
        return labelAtk;
    }

    /**
     * @param labelAtk the labelAtk to set
     */
    public void setLabelAtk(javax.swing.JLabel labelAtk) {
        this.labelAtk = labelAtk;
    }

    /**
     * @return the labelDef
     */
    public javax.swing.JLabel getLabelDef() {
        return labelDef;
    }

    /**
     * @param labelDef the labelDef to set
     */
    public void setLabelDef(javax.swing.JLabel labelDef) {
        this.labelDef = labelDef;
    }

    /**
     * @return the labelHP
     */
    public javax.swing.JLabel getLabelHP() {
        return labelHP;
    }

    /**
     * @param labelHP the labelHP to set
     */
    public void setLabelHP(javax.swing.JLabel labelHP) {
        this.labelHP = labelHP;
    }

    /**
     * @return the labelbox
     */
    public javax.swing.JLabel getLabelbox() {
        return labelbox;
    }

    /**
     * @param labelbox the labelbox to set
     */
    public void setLabelbox(javax.swing.JLabel labelbox) {
        this.labelbox = labelbox;
    }

    /**
     * @return the winorlose
     */
    public javax.swing.JPanel getWinorlose() {
        return winorlose;
    }

    /**
     * @param winorlose the winorlose to set
     */
    public void setWinorlose(javax.swing.JPanel winorlose) {
        this.winorlose = winorlose;
    }
}
